[profile.release]
# strip = true  # Automatically strip symbols from the binary.
# opt-level = "z"
# lto = true
# panic = "abort"

[package]
name = "prefstore"
version = "0.1.0"
edition = "2021"
author = ["visnk"]
description = "Simple multi platform Rust crate for storing application preferences and settings."
license = "MIT"
homepage = "https://github.com/visnkmr/prefstore"
repository = "https://github.com/visnkmr/prefstore"
keywords = ["settings", "preferences", "config", "options"]
categories = ["config"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"